[window]
dimensions = { columns = 115, lines = 30 }
padding = { x = 10, y = 10 }
opacity = 0.98

[font]
normal = { family = "JetBrainsMono NF", style = "normal" }
size = 11

[colors]
[colors.primary]
background = "#1C1C1F"
[colors.normal]
black = "#241F31"
red = "#C01C28"
green = "#2EC27E"
yellow = "#F5C211"
blue = "#1E78E4"
magenta = "#9841BB"
cyan = "#0AB9DC"
white = "#C0BFBC"
[colors.bright]
black = "#5E5C64"
red = "#ED333B"
green = "#57E389"
yellow = "#F8E45C"
blue = "#51A1FF"
magenta = "#C061CB"
cyan = "#4FD2FD"
white = "#F6F5F4"

[cursor]
style = { shape = "Beam", blinking = "On"}
unfocused_hollow = false
